# Server settings(ServerProperties)
server:
  port: 8080
  address: 127.0.0.1
  session:
    timeout: 30
  context-path: /
  # Tomcat specifics
  tomcat:
    accesslog:
      enabled: false
    protocol-header: x-forwarded-proto
    remote-ip-header: x-forwarded-for
    basedir:
    background-processor-delay: 30 # secs
# spring default database configration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 1315164597
    driverClassName: com.mysql.jdbc.Driver
  # JPA configration
  # Specify the DBMS
  jpa:
    database: MYSQL
    # Show or not log for each sql query
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate:
      ddl-auto: update
    # stripped before adding them to the entity manager)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
## security configration
#security:
#  basic:
#    enabled: true
#  user:
#    name: root
#    password: foo
#    role: USER